import { Clock, Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { COMPANY } from '../data';

export default function ContactView() {
  return (
    <div>
      <section className="bg-brand-900 py-20 text-white"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-gold">Contact</p><h1 className="mt-4 text-4xl font-extrabold sm:text-5xl">Get in touch with Capella</h1><p className="mt-6 max-w-3xl text-sm leading-relaxed text-slate-200">Contact us by phone or email to discuss your business requirements. WhatsApp and social media details will be published when they are supplied by the client.</p></div></section>
      <section className="mx-auto grid max-w-7xl gap-6 px-6 py-20 sm:px-8 md:grid-cols-2 lg:px-12"><div className="rounded border border-slate-200 p-7"><MapPin className="h-7 w-7 text-brand-gold" /><h2 className="mt-5 text-lg font-bold text-brand-900">Address</h2><p className="mt-2 text-sm text-slate-600">{COMPANY.address}</p></div><div className="rounded border border-slate-200 p-7"><Phone className="h-7 w-7 text-brand-gold" /><h2 className="mt-5 text-lg font-bold text-brand-900">Phone</h2><div className="mt-2 space-y-1 text-sm"><a className="block text-slate-600 hover:text-brand-900" href={`tel:${COMPANY.phones[0]}`}>{COMPANY.phones[0]}</a><a className="block text-slate-600 hover:text-brand-900" href={`tel:${COMPANY.phones[1]}`}>{COMPANY.phones[1]}</a></div></div><div className="rounded border border-slate-200 p-7"><MessageCircle className="h-7 w-7 text-brand-gold" /><h2 className="mt-5 text-lg font-bold text-brand-900">WhatsApp</h2><p className="mt-2 text-sm text-slate-600">Pending from client</p></div><div className="rounded border border-slate-200 p-7"><Mail className="h-7 w-7 text-brand-gold" /><h2 className="mt-5 text-lg font-bold text-brand-900">Email</h2><a className="mt-2 block text-sm text-slate-600 hover:text-brand-900" href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a></div></section>
      <section className="bg-slate-50 py-16"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-12"><div className="flex items-start gap-4 rounded border-l-4 border-brand-gold bg-white p-7"><Clock className="mt-1 h-6 w-6 shrink-0 text-brand-gold" /><div><h2 className="text-xl font-bold text-brand-900">Business Hours</h2><ul className="mt-3 space-y-1 text-sm text-slate-600">{COMPANY.hours.map((hours) => <li key={hours}>{hours}</li>)}</ul></div></div><p className="mt-8 text-sm text-slate-600">Social media details are pending from the client.</p></div></section>
    </div>
  );
}
